name: mowgli
description: Mowgli App
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1

  # Dart
  freezed_annotation: ^0.12.0
  kotlin_flavor: ^0.1.0
  uuid: ^2.2.2

  # Network
  dio: ^3.0.10
  retrofit: ^1.3.4+1
  json_annotation: ^3.1.0

  # Architecture / state management
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  flutter_bloc: ^6.0.6
  get_it: ^4.0.4

  # Storage
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  # Logs
  flutter_fimber: ^0.4.4
  flutter_fimber_filelogger: ^1.2.0

  # Device specific
  connectivity: ^0.4.9+5
  device_info: ^0.4.2+9
  package_info: ^0.4.3
  share: ^0.6.5+3
  ip_geolocation_api:
    git: 'git@github.com:g123k/dart-ip-geolocation-api.git'

  # Push
  firebase_messaging: ^7.0.3

  # Notifications
  flutter_local_notifications: ^2.0.1+1
  app_settings: 4.0.2

  # Analytics
  amplitude_flutter: ^2.2.1

  # Crashlytics
  firebase_crashlytics: ^0.2.1+1

  # User feedbacks
  wiredash:
    git: git@github.com:g123k/wiredash-sdk.git

  # UI
  google_fonts: ^1.1.1
  flutter_svg: ^0.19.0
  animations: ^1.1.2
  css_text: ^2.1.0
  vertical_calendar: ^1.0.1+6
  auto_size_text: ^2.1.0
  cached_network_image: ^2.3.3
  overlay_support: ^1.0.5
  listview_utils:
    git:
      url: 'git@github.com:g123k/flutter-listutils.git'
      ref: 'mowgli'

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator:
  json_serializable: any
  hive_generator: ^0.8.1
  freezed:

  build_runner:

  # Custom implementation of Flappy Translator
  flappy_translator:
    git:
      url: 'git@github.com:g123k/FlappyTranslator.git'

flutter:
  uses-material-design: true

  assets:
    - res/images/

  fonts:
   - family:  AppIcons
     fonts:
      - asset: res/fonts/AppIcons.ttf

flappy_translator:
  input_file_path: "res/i18n/translations.csv"
  output_dir: "lib/ui/resources"
  file_name: "translations"
  class_name: "Translations"
  delimiter: ","
  start_index: 1
  depend_on_context: true
  use_single_quotes: true
  replace_no_break_spaces: false
  grouped_keys:
    - calendarDay

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true